### ISSUE TITLE
Fails when do a dig

### ISSUE THREAD

**Issue by dsokolov** [dsokolov/juggler#5]
java.lang.IllegalArgumentException: No view found for id 0x7f0f00d4  for fragment MainNavigationFragment{719c894 #2 id=0x7f0f00d4}
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1059)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                            at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:971)
                                                                            at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1722)
                                                                            at android.support.v4.app.FragmentManagerImpl$3.run(FragmentManager.java:593)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dsokolov** [comment]
fixed in 0.0.31
